name: autobrand_director
description: " autobrand_director is a Flutter application that serves as a director for managing and organizing various brands. It provides a user-friendly interface for users to view, add, and manage their brand information efficiently. The app is designed to help users keep track of their brands, including details such as brand name, logo, description, and other relevant information. With its intuitive design and powerful features, autobrand_director aims to simplify brand management for users and enhance their overall experience."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.2
  firebase_auth: ^6.2.0
  go_router: ^17.1.0
  firebase_core: ^4.5.0
  cloud_firestore: ^6.1.3
  flutter_svg: ^2.2.4
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/brand.svg



